### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Mstrodl**

### CODE REVIEW

**Comment by xela-zone** [comment]
requierements.txt  -> requirements.txt

**Comment by xela-zone** [comment]
this needs to be rebased due to the solution to #1

**Comment by Mstrodl** [comment]
[:blobdogtongue:](http://i.stole-a-me.me/f0b536.png)

**Comment by tilda** [comment]
This branch has conflicts that must be resolved

**Comment by xela-zone** [comment]
this PR has had no motion for almost a month. 
closing.

**Pull request closed without merging**
